name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
        
    - name: Dependencies
      run: make deps

    - name: Code generation
      run: make generate

    - name: Test
      run: make test

    - name: Coverage report
      run: make cover-report

    - uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage*.*